#!/bin/bash

# Inbox Zero Automated Setup Script
# This script will install and configure the open-source Inbox Zero email assistant

set -e  # Exit on any error

echo "🚀 INBOX ZERO AUTOMATED SETUP"
echo "=============================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Check if we're in the right directory
SETUP_DIR="/Users/dancumberland/Documents/Work/AI Projects & Training Docs/Dan_Personal_Brand/AI_Tools/Gmail_Voice_Doc"
cd "$SETUP_DIR"

print_info "Setting up Inbox Zero in: $SETUP_DIR"

# Step 1: Check prerequisites
print_info "Step 1: Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    print_error "Node.js is not installed. Please install Node.js >= 18.0.0 from https://nodejs.org/"
    exit 1
fi

NODE_VERSION=$(node --version | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
    print_error "Node.js version must be >= 18.0.0. Current version: $(node --version)"
    exit 1
fi
print_status "Node.js $(node --version) is installed"

# Check/Install pnpm
if ! command -v pnpm &> /dev/null; then
    print_info "Installing pnpm..."
    npm install -g pnpm
fi
print_status "pnpm $(pnpm --version) is installed"

# Check Docker
if ! command -v docker &> /dev/null; then
    print_warning "Docker is not installed. We'll use cloud services instead."
    USE_DOCKER=false
else
    print_status "Docker is available"
    USE_DOCKER=true
fi

# Step 2: Clone Inbox Zero repository
print_info "Step 2: Cloning Inbox Zero repository..."

if [ -d "inbox-zero" ]; then
    print_info "Inbox Zero directory already exists. Updating..."
    cd inbox-zero
    git pull
else
    git clone https://github.com/elie222/inbox-zero.git
    cd inbox-zero
fi
print_status "Repository cloned/updated"

# Step 3: Install dependencies
print_info "Step 3: Installing dependencies..."
pnpm install
print_status "Dependencies installed"

# Step 4: Generate secrets
print_info "Step 4: Generating secure secrets..."

NEXTAUTH_SECRET=$(openssl rand -hex 32)
EMAIL_ENCRYPT_SECRET=$(openssl rand -hex 32)
EMAIL_ENCRYPT_SALT=$(openssl rand -hex 16)

print_status "Secrets generated"

# Step 5: Create .env file
print_info "Step 5: Creating environment configuration..."

cat > apps/web/.env << EOF
# Generated by Inbox Zero Setup Script
# $(date)

# Secrets
NEXTAUTH_SECRET="$NEXTAUTH_SECRET"
EMAIL_ENCRYPT_SECRET="$EMAIL_ENCRYPT_SECRET"
EMAIL_ENCRYPT_SALT="$EMAIL_ENCRYPT_SALT"

# Base URL (adjust if needed)
NEXTAUTH_URL="http://localhost:3000"

# Database (using Vercel Postgres for simplicity)
# You'll need to set these up manually or use Docker
POSTGRES_URL=""
POSTGRES_PRISMA_URL=""
POSTGRES_URL_NO_SSL=""
POSTGRES_URL_NON_POOLING=""
POSTGRES_USER=""
POSTGRES_HOST=""
POSTGRES_PASSWORD=""
POSTGRES_DATABASE=""

# Redis (using Upstash for simplicity)
UPSTASH_REDIS_URL=""
UPSTASH_REDIS_TOKEN=""

# Google OAuth (we'll copy from your existing credentials)
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""

# OpenAI for AI features
OPENAI_API_KEY=""

# Optional: Resend for email sending
RESEND_API_KEY=""

# Optional: PostHog for analytics
NEXT_PUBLIC_POSTHOG_KEY=""
NEXT_PUBLIC_POSTHOG_HOST=""

# Optional: Lemon Squeezy for payments
LEMON_SQUEEZY_API_KEY=""
LEMON_SQUEEZY_SIGNING_SECRET=""

# Optional: Loops for email marketing
LOOPS_API_KEY=""

# Optional: Tinybird for analytics
TINYBIRD_API_KEY=""

# Vercel settings
MAX_DURATION=300
EOF

print_status "Environment file created"

# Step 6: Copy Google OAuth credentials
print_info "Step 6: Configuring Google OAuth..."

OAUTH_FILE="/Users/dancumberland/MCPs/windsurf-mcp/gcp-oauth.keys.json"
if [ -f "$OAUTH_FILE" ]; then
    GOOGLE_CLIENT_ID=$(jq -r '.web.client_id' "$OAUTH_FILE")
    GOOGLE_CLIENT_SECRET=$(jq -r '.web.client_secret' "$OAUTH_FILE")
    
    # Update .env with Google credentials
    sed -i '' "s/GOOGLE_CLIENT_ID=\"\"/GOOGLE_CLIENT_ID=\"$GOOGLE_CLIENT_ID\"/" apps/web/.env
    sed -i '' "s/GOOGLE_CLIENT_SECRET=\"\"/GOOGLE_CLIENT_SECRET=\"$GOOGLE_CLIENT_SECRET\"/" apps/web/.env
    
    print_status "Google OAuth credentials configured"
else
    print_warning "Google OAuth file not found at $OAUTH_FILE"
    print_info "You'll need to manually add GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET to apps/web/.env"
fi

# Step 7: Set up database and Redis
print_info "Step 7: Setting up database and Redis..."

if [ "$USE_DOCKER" = true ]; then
    print_info "Using Docker for local development..."
    
    # Create docker-compose.yml for local services
    cat > docker-compose.yml << EOF
version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: inbox_zero
      POSTGRES_USER: inbox_zero
      POSTGRES_PASSWORD: inbox_zero_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
EOF

    # Start services
    docker-compose up -d
    
    # Wait for services to start
    sleep 10
    
    # Update .env with local database URLs
    sed -i '' 's/POSTGRES_URL=""/POSTGRES_URL="postgresql:\/\/inbox_zero:inbox_zero_password@localhost:5432\/inbox_zero"/' apps/web/.env
    sed -i '' 's/UPSTASH_REDIS_URL=""/UPSTASH_REDIS_URL="redis:\/\/localhost:6379"/' apps/web/.env
    sed -i '' 's/UPSTASH_REDIS_TOKEN=""/UPSTASH_REDIS_TOKEN="local_redis_token"/' apps/web/.env
    
    print_status "Local database and Redis started with Docker"
else
    print_warning "Docker not available. You'll need to set up cloud services:"
    print_info "1. Create a PostgreSQL database (Vercel Postgres, Supabase, or similar)"
    print_info "2. Create a Redis instance (Upstash, Redis Cloud, or similar)"
    print_info "3. Update the database URLs in apps/web/.env"
fi

# Step 8: Run database migrations
print_info "Step 8: Setting up database schema..."

if [ "$USE_DOCKER" = true ]; then
    # Wait a bit more for PostgreSQL to be ready
    sleep 5
    
    cd apps/web
    pnpm prisma generate
    pnpm prisma db push
    cd ../..
    
    print_status "Database schema created"
else
    print_warning "Skipping database setup. Run 'pnpm prisma db push' after configuring database URLs"
fi

# Step 9: Create startup script
print_info "Step 9: Creating startup script..."

cat > start_inbox_zero.sh << EOF
#!/bin/bash

# Inbox Zero Startup Script
echo "🚀 Starting Inbox Zero..."

# Start Docker services if using Docker
if [ -f "docker-compose.yml" ]; then
    echo "Starting database services..."
    docker-compose up -d
    sleep 5
fi

# Start the application
echo "Starting Inbox Zero web application..."
cd apps/web
pnpm dev

echo "Inbox Zero is running at http://localhost:3000"
EOF

chmod +x start_inbox_zero.sh

print_status "Startup script created"

# Step 10: Create configuration guide
print_info "Step 10: Creating configuration guide..."

cat > SETUP_COMPLETE.md << EOF
# 🎉 Inbox Zero Setup Complete!

Your Inbox Zero installation is ready! Here's what was set up:

## ✅ What's Configured:
- ✅ Repository cloned and dependencies installed
- ✅ Environment file created with secure secrets
- ✅ Google OAuth credentials configured
$(if [ "$USE_DOCKER" = true ]; then echo "- ✅ Local PostgreSQL and Redis running in Docker"; else echo "- ⚠️  Database and Redis need manual setup"; fi)
- ✅ Startup script created

## 🚀 Next Steps:

### 1. Configure Required Services
You need to set up these services and add their credentials to \`apps/web/.env\`:

**Required:**
- **OpenAI API Key**: Get from https://platform.openai.com/api-keys
  - Add to \`OPENAI_API_KEY\` in .env file

$(if [ "$USE_DOCKER" = false ]; then echo "**Database & Redis (if not using Docker):**
- **PostgreSQL**: Use Vercel Postgres, Supabase, or similar
- **Redis**: Use Upstash, Redis Cloud, or similar
- Update all POSTGRES_* and UPSTASH_REDIS_* variables in .env"; fi)

**Optional but Recommended:**
- **Resend** (for sending emails): https://resend.com/
- **PostHog** (for analytics): https://posthog.com/

### 2. Update Google OAuth Redirect URIs
In your Google Cloud Console, add these redirect URIs:
- \`http://localhost:3000/api/auth/callback/google\`
- \`https://yourdomain.com/api/auth/callback/google\` (for production)

### 3. Start Inbox Zero
\`\`\`bash
./start_inbox_zero.sh
\`\`\`

### 4. Access the Application
Open http://localhost:3000 in your browser

### 5. Configure AI Rules
Once logged in, you can set up AI rules to work with your Gmail labels:
- @Action ⚡️/Respond
- @Action ⚡️/Todo  
- @Action ⚡️/Schedule
- @Prospect 💰/Hot-10d
- @Waiting ⏳/7d
- @Waiting ⏳/14d
- @Reference/Inboxes/* (AI, HARO, News, Indy Acquisitions)
- @Projects/*
- @Archive/*

## 📁 Important Files:
- \`apps/web/.env\` - Environment configuration
- \`start_inbox_zero.sh\` - Startup script
- \`docker-compose.yml\` - Local services (if using Docker)

## 🔧 Troubleshooting:
If you encounter issues:
1. Check that all required environment variables are set
2. Ensure database is accessible
3. Verify Google OAuth credentials
4. Check the logs in the terminal

## 📚 Documentation:
- Inbox Zero Docs: https://docs.getinboxzero.com
- GitHub Repository: https://github.com/elie222/inbox-zero

Happy email management! 🎯
EOF

print_status "Setup guide created"

# Final summary
echo ""
echo "🎉 INBOX ZERO SETUP COMPLETE!"
echo "=============================="
print_status "Repository cloned and configured"
print_status "Dependencies installed"
print_status "Environment file created with secrets"
print_status "Google OAuth credentials configured"
$(if [ "$USE_DOCKER" = true ]; then echo 'print_status "Local database and Redis started"'; else echo 'print_warning "Database and Redis need manual configuration"'; fi)
print_status "Startup script created"

echo ""
print_info "📋 NEXT STEPS:"
echo "1. 🔑 Add your OpenAI API key to apps/web/.env"
$(if [ "$USE_DOCKER" = false ]; then echo "2. 🗄️  Set up PostgreSQL and Redis (or use Docker)"; fi)
echo "3. 🚀 Run: ./start_inbox_zero.sh"
echo "4. 🌐 Open: http://localhost:3000"
echo "5. 📖 Read: SETUP_COMPLETE.md for detailed instructions"

echo ""
print_info "📁 Setup completed in: $(pwd)"
print_info "📄 Full instructions: $(pwd)/SETUP_COMPLETE.md"

echo ""
echo "🎯 Your Gmail labels are perfectly organized and ready for AI automation!"
