#!/bin/bash

# Inbox Zero Automated Setup Script (Fixed)
# This script will install and configure the open-source Inbox Zero email assistant

set -e  # Exit on any error

echo "🚀 INBOX ZERO AUTOMATED SETUP (FIXED)"
echo "====================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Check if we're in the right directory
SETUP_DIR="/Users/dancumberland/Documents/Work/AI Projects & Training Docs/Dan_Personal_Brand/AI_Tools/Gmail_Voice_Doc"
cd "$SETUP_DIR"

print_info "Setting up Inbox Zero in: $SETUP_DIR"

# Step 1: Check prerequisites
print_info "Step 1: Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    print_error "Node.js is not installed. Please install Node.js >= 18.0.0 from https://nodejs.org/"
    exit 1
fi

NODE_VERSION=$(node --version | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
    print_error "Node.js version must be >= 18.0.0. Current version: $(node --version)"
    exit 1
fi
print_status "Node.js $(node --version) is installed"

# Check/Install pnpm using corepack (no sudo required)
if ! command -v pnpm &> /dev/null; then
    print_info "Installing pnpm using corepack (no sudo required)..."
    corepack enable
    corepack prepare pnpm@latest --activate
fi

# Verify pnpm is working
if command -v pnpm &> /dev/null; then
    print_status "pnpm $(pnpm --version) is ready"
else
    print_warning "pnpm installation failed. Using npm instead..."
    PACKAGE_MANAGER="npm"
fi

# Set package manager
if command -v pnpm &> /dev/null; then
    PACKAGE_MANAGER="pnpm"
else
    PACKAGE_MANAGER="npm"
fi

print_info "Using package manager: $PACKAGE_MANAGER"

# Check Docker
if ! command -v docker &> /dev/null; then
    print_warning "Docker is not installed. We'll use cloud services instead."
    USE_DOCKER=false
else
    print_status "Docker is available"
    USE_DOCKER=true
fi

# Step 2: Clone Inbox Zero repository
print_info "Step 2: Cloning Inbox Zero repository..."

if [ -d "inbox-zero" ]; then
    print_info "Inbox Zero directory already exists. Updating..."
    cd inbox-zero
    git pull
else
    git clone https://github.com/elie222/inbox-zero.git
    cd inbox-zero
fi
print_status "Repository cloned/updated"

# Step 3: Install dependencies
print_info "Step 3: Installing dependencies..."
if [ "$PACKAGE_MANAGER" = "pnpm" ]; then
    pnpm install
else
    npm install
fi
print_status "Dependencies installed"

# Step 4: Generate secrets
print_info "Step 4: Generating secure secrets..."

NEXTAUTH_SECRET=$(openssl rand -hex 32)
EMAIL_ENCRYPT_SECRET=$(openssl rand -hex 32)
EMAIL_ENCRYPT_SALT=$(openssl rand -hex 16)

print_status "Secrets generated"

# Step 5: Create .env file
print_info "Step 5: Creating environment configuration..."

cat > apps/web/.env << EOF
# Generated by Inbox Zero Setup Script
# $(date)

# Secrets
NEXTAUTH_SECRET="$NEXTAUTH_SECRET"
EMAIL_ENCRYPT_SECRET="$EMAIL_ENCRYPT_SECRET"
EMAIL_ENCRYPT_SALT="$EMAIL_ENCRYPT_SALT"

# Base URL (adjust if needed)
NEXTAUTH_URL="http://localhost:3000"

# Database URLs (will be configured based on setup choice)
POSTGRES_URL=""
POSTGRES_PRISMA_URL=""
POSTGRES_URL_NO_SSL=""
POSTGRES_URL_NON_POOLING=""
POSTGRES_USER=""
POSTGRES_HOST=""
POSTGRES_PASSWORD=""
POSTGRES_DATABASE=""

# Redis
UPSTASH_REDIS_URL=""
UPSTASH_REDIS_TOKEN=""

# Google OAuth (we'll copy from your existing credentials)
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""

# OpenAI for AI features (REQUIRED - you need to add this)
OPENAI_API_KEY=""

# Optional services
RESEND_API_KEY=""
NEXT_PUBLIC_POSTHOG_KEY=""
NEXT_PUBLIC_POSTHOG_HOST=""
LEMON_SQUEEZY_API_KEY=""
LEMON_SQUEEZY_SIGNING_SECRET=""
LOOPS_API_KEY=""
TINYBIRD_API_KEY=""

# Vercel settings
MAX_DURATION=300
EOF

print_status "Environment file created"

# Step 6: Copy Google OAuth credentials
print_info "Step 6: Configuring Google OAuth..."

OAUTH_FILE="/Users/dancumberland/MCPs/windsurf-mcp/gcp-oauth.keys.json"
if [ -f "$OAUTH_FILE" ]; then
    if command -v jq &> /dev/null; then
        GOOGLE_CLIENT_ID=$(jq -r '.web.client_id' "$OAUTH_FILE")
        GOOGLE_CLIENT_SECRET=$(jq -r '.web.client_secret' "$OAUTH_FILE")
        
        # Update .env with Google credentials
        sed -i '' "s/GOOGLE_CLIENT_ID=\"\"/GOOGLE_CLIENT_ID=\"$GOOGLE_CLIENT_ID\"/" apps/web/.env
        sed -i '' "s/GOOGLE_CLIENT_SECRET=\"\"/GOOGLE_CLIENT_SECRET=\"$GOOGLE_CLIENT_SECRET\"/" apps/web/.env
        
        print_status "Google OAuth credentials configured"
    else
        print_warning "jq not found. Please manually add Google OAuth credentials to apps/web/.env"
    fi
else
    print_warning "Google OAuth file not found at $OAUTH_FILE"
    print_info "You'll need to manually add GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET to apps/web/.env"
fi

# Step 7: Set up database and Redis
print_info "Step 7: Setting up database and Redis..."

if [ "$USE_DOCKER" = true ]; then
    print_info "Setting up local development with Docker..."
    
    # Create docker-compose.yml for local services
    cat > docker-compose.yml << EOF
version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: inbox_zero
      POSTGRES_USER: inbox_zero
      POSTGRES_PASSWORD: inbox_zero_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inbox_zero"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:
EOF

    # Start services
    print_info "Starting Docker services..."
    docker-compose up -d
    
    # Wait for services to be healthy
    print_info "Waiting for services to be ready..."
    sleep 15
    
    # Update .env with local database URLs
    LOCAL_DB_URL="postgresql://inbox_zero:inbox_zero_password@localhost:5432/inbox_zero"
    sed -i '' "s|POSTGRES_URL=\"\"|POSTGRES_URL=\"$LOCAL_DB_URL\"|" apps/web/.env
    sed -i '' "s|POSTGRES_PRISMA_URL=\"\"|POSTGRES_PRISMA_URL=\"$LOCAL_DB_URL\"|" apps/web/.env
    sed -i '' "s|POSTGRES_URL_NO_SSL=\"\"|POSTGRES_URL_NO_SSL=\"$LOCAL_DB_URL\"|" apps/web/.env
    sed -i '' "s|POSTGRES_URL_NON_POOLING=\"\"|POSTGRES_URL_NON_POOLING=\"$LOCAL_DB_URL\"|" apps/web/.env
    sed -i '' 's|UPSTASH_REDIS_URL=""|UPSTASH_REDIS_URL="redis://localhost:6379"|' apps/web/.env
    sed -i '' 's|UPSTASH_REDIS_TOKEN=""|UPSTASH_REDIS_TOKEN="local_redis_token"|' apps/web/.env
    
    print_status "Local database and Redis configured"
    
    # Step 8: Run database migrations
    print_info "Step 8: Setting up database schema..."
    
    cd apps/web
    if [ "$PACKAGE_MANAGER" = "pnpm" ]; then
        pnpm prisma generate
        pnpm prisma db push
    else
        npx prisma generate
        npx prisma db push
    fi
    cd ../..
    
    print_status "Database schema created"
else
    print_warning "Docker not available. You'll need to set up cloud services:"
    print_info "1. Create a PostgreSQL database (Vercel Postgres, Supabase, or similar)"
    print_info "2. Create a Redis instance (Upstash, Redis Cloud, or similar)"
    print_info "3. Update the database URLs in apps/web/.env"
fi

# Step 9: Create startup script
print_info "Step 9: Creating startup script..."

cat > start_inbox_zero.sh << EOF
#!/bin/bash

# Inbox Zero Startup Script
echo "🚀 Starting Inbox Zero..."

# Start Docker services if using Docker
if [ -f "docker-compose.yml" ]; then
    echo "Starting database services..."
    docker-compose up -d
    echo "Waiting for services to be ready..."
    sleep 10
fi

# Start the application
echo "Starting Inbox Zero web application..."
cd apps/web

if command -v pnpm &> /dev/null; then
    pnpm dev
else
    npm run dev
fi
EOF

chmod +x start_inbox_zero.sh

print_status "Startup script created"

# Step 10: Create quick start guide
print_info "Step 10: Creating quick start guide..."

cat > QUICK_START.md << EOF
# 🚀 Inbox Zero Quick Start

## ✅ Setup Complete!
Your Inbox Zero installation is ready. Here's what's configured:

- ✅ Repository cloned and dependencies installed
- ✅ Environment file created with secure secrets
- ✅ Google OAuth credentials configured
$(if [ "$USE_DOCKER" = true ]; then echo "- ✅ Local PostgreSQL and Redis running"; else echo "- ⚠️  Database and Redis need manual setup"; fi)

## 🔑 REQUIRED: Add Your OpenAI API Key

**Before starting, you MUST add your OpenAI API key:**

1. Get your API key from: https://platform.openai.com/api-keys
2. Edit \`apps/web/.env\`
3. Add your key: \`OPENAI_API_KEY="sk-your-key-here"\`

## 🚀 Start Inbox Zero

\`\`\`bash
./start_inbox_zero.sh
\`\`\`

Then open: http://localhost:3000

## 🎯 Your Perfect Gmail Labels

Your Gmail is already perfectly organized with these labels:

**Action Buckets:**
- @Action ⚡️/Respond
- @Action ⚡️/Todo  
- @Action ⚡️/Schedule

**Prospect Management:**
- @Prospect 💰/Hot-10d

**Waiting/Reminders:**
- @Waiting ⏳/7d
- @Waiting ⏳/14d

**Reference Organization:**
- @Reference/Inboxes/ (AI, HARO, News, Indy Acquisitions)
- @Reference/Courses/ (Break An Egg, etc.)
- @Reference/Swipes/ (General, Social)

**Project Management:**
- @Projects/ (MRR Method, Networking, REIT, etc.)

**Archive:**
- @Archive/Projects/ (completed projects)
- @Archive/Misc/ (other archived items)

## 🤖 Setting Up AI Rules

Once logged in, you can create AI rules like:

\`\`\`
If email is from "haro@helpareporter.com":
- Add label "@Reference/Inboxes/HARO"
- Archive email

If email contains "schedule" or "calendar":
- Add label "@Action ⚡️/Schedule"
- Keep in inbox

If email is from a prospect and older than 10 days:
- Add label "@Prospect 💰/Hot-10d"
- Keep in inbox for follow-up
\`\`\`

## 🔧 Troubleshooting

**If startup fails:**
1. Check that OpenAI API key is set
2. Ensure Docker services are running (if using Docker)
3. Check the terminal for error messages

**Database issues:**
- If using Docker: \`docker-compose restart\`
- If using cloud: Check your database connection strings

## 📚 Resources

- Inbox Zero Docs: https://docs.getinboxzero.com
- GitHub: https://github.com/elie222/inbox-zero

Happy email automation! 🎉
EOF

print_status "Quick start guide created"

# Final summary
echo ""
echo "🎉 INBOX ZERO SETUP COMPLETE!"
echo "=============================="
print_status "Repository cloned and configured"
print_status "Dependencies installed with $PACKAGE_MANAGER"
print_status "Environment file created with secrets"
print_status "Google OAuth credentials configured"
$(if [ "$USE_DOCKER" = true ]; then echo 'print_status "Local database and Redis started"'; else echo 'print_warning "Database and Redis need manual configuration"'; fi)
print_status "Startup script created"

echo ""
print_info "🔑 CRITICAL NEXT STEP:"
echo "   Add your OpenAI API key to apps/web/.env"
echo "   Get it from: https://platform.openai.com/api-keys"

echo ""
print_info "🚀 TO START INBOX ZERO:"
echo "   ./start_inbox_zero.sh"

echo ""
print_info "🌐 THEN OPEN:"
echo "   http://localhost:3000"

echo ""
print_info "📖 READ THE GUIDE:"
echo "   cat QUICK_START.md"

echo ""
print_status "Your Gmail labels are perfectly organized and ready for AI automation!"
echo ""
print_info "Setup completed in: $(pwd)"
